name: main
on: [workflow_dispatch]
jobs:
  main:
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#assigning-permissions-to-a-specific-job
    # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
    #permissions: write-all
    steps:
      - name: Patch this repository
        run: |
          # https://docs.github.com/en/rest/repos/repos#update-a-repository
          curl -L --fail-with-body \
            -X PATCH \
            -H "Authorization: token ${{ github.token }}"\
            https://api.github.com/repos/TomasHubelbauer/github-token-edit-another-repo \
            -d '{"description":"Last tested at $(date -Iseconds)","homepage":"https://hubelbauer.net/$(date -Iseconds)"}'
